database:
  driver-class-name: org.postgresql.Driver

aws:
  instance-profile: true
  secretsmanager:
    name: /${spring.profiles.active}/distribution/spring-service-template
  secretslist: >
    database.username,
    database.password,
    database.host,
    database.port,
    database.name

server:
  port: 8081
  servlet:
    context-path: /

cloud:
  aws:
    credentials:
      access-key: x
      secret-key: x
      instance-profile: false
    region:
      static: us-west-2
    stack:
      auto: false

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: readiness
        info: healthz
  endpoint:
    health:
      show-details: always

info:
  service:
    name: Spring Service Template
    description: Template service to provide an easy starter for new spring boot servies
    version: v1.0.0-SNAPSHOT